### ISSUE TITLE
Found Bug n Shit

### ISSUE THREAD

**Issue by FadTheChad** [Phentix/Phentix#2]
https://github.com/Phentix/Phentix/blob/b3287474911a1044fe00dae3de66abb8eff9b3a5/src/commands/message/moderation/ban.ts#L15-L16

In this, .fetch() is being used. Theres 2 cases where bot will go die:

## Case 1 (if no arg is defined)
The member variable will be basically be a collection ALL members of the guild since well, args[0] is empty, and .fetch() fetches all if no param is defined properly. can be fixed by doing `if (member || !args[0])` check

## Case 2 (if arg is defined but not a member)
if i do `t!ban test`, this will most likely throw an error. simple solution is to .catch() at the end of the fetch

**Comment by Conrad36** [comment]
fixed
